package life.majiang.community.community.mapper;

import java.util.List;
import life.majiang.community.community.model.TagCategory;
import life.majiang.community.community.model.TagCategoryExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TagCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tagcategory
     *
     * @mbggenerated Mon Mar 30 20:52:04 CST 2020
     */
    int countByExample(TagCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tagcategory
     *
     * @mbggenerated Mon Mar 30 20:52:04 CST 2020
     */
    int deleteByExample(TagCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tagcategory
     *
     * @mbggenerated Mon Mar 30 20:52:04 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tagcategory
     *
     * @mbggenerated Mon Mar 30 20:52:04 CST 2020
     */
    int insert(TagCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tagcategory
     *
     * @mbggenerated Mon Mar 30 20:52:04 CST 2020
     */
    int insertSelective(TagCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tagcategory
     *
     * @mbggenerated Mon Mar 30 20:52:04 CST 2020
     */
    List<TagCategory> selectByExampleWithRowbounds(TagCategoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tagcategory
     *
     * @mbggenerated Mon Mar 30 20:52:04 CST 2020
     */
    List<TagCategory> selectByExample(TagCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tagcategory
     *
     * @mbggenerated Mon Mar 30 20:52:04 CST 2020
     */
    TagCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tagcategory
     *
     * @mbggenerated Mon Mar 30 20:52:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") TagCategory record, @Param("example") TagCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tagcategory
     *
     * @mbggenerated Mon Mar 30 20:52:04 CST 2020
     */
    int updateByExample(@Param("record") TagCategory record, @Param("example") TagCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tagcategory
     *
     * @mbggenerated Mon Mar 30 20:52:04 CST 2020
     */
    int updateByPrimaryKeySelective(TagCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tagcategory
     *
     * @mbggenerated Mon Mar 30 20:52:04 CST 2020
     */
    int updateByPrimaryKey(TagCategory record);
}