package life.majiang.community.community.model;

public class TagCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tagcategory.id
     *
     * @mbggenerated Mon Mar 30 20:52:04 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tagcategory.category_name
     *
     * @mbggenerated Mon Mar 30 20:52:04 CST 2020
     */
    private String categoryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tagcategory.id
     *
     * @return the value of tagcategory.id
     *
     * @mbggenerated Mon Mar 30 20:52:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tagcategory.id
     *
     * @param id the value for tagcategory.id
     *
     * @mbggenerated Mon Mar 30 20:52:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tagcategory.category_name
     *
     * @return the value of tagcategory.category_name
     *
     * @mbggenerated Mon Mar 30 20:52:04 CST 2020
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tagcategory.category_name
     *
     * @param categoryName the value for tagcategory.category_name
     *
     * @mbggenerated Mon Mar 30 20:52:04 CST 2020
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }
}